markdown: kramdown
highlighter: rouge
permalink: /:categories/:title.html
excerpt_separator: "<!-- more -->"
auto: auto

github: slevin1994
author: "slevin1994"
email: slevin1994#163.com
name: "slevin1994's Blog"
baseurl: /
url: https://slevin1994.github.io
domain: slevin1994.github.io

all_categories: [
  ["android", "Android开发"], 
  ["react", "React Native"],
  ["web", "Web建站"], 
  ["linux", "Linux相关"],
  ["git", "git用法"],
  ["program", "软件开发"],
  ["vps", "VPS"],
  ["other", "杂记"],
  ["read", "书摘"], 
  ["about", "关于"]
]

paginate: 10
paginate_path: "index_:num"

index_layout: "index.html"
category_layout: "_layouts/category.html"
tag_layout: "_layouts/tag.html"

#不使用gems库中的jekyll-paginate-category
#使用基于jekyll-paginate改写的的栏目分页插件，所以jekyll-paginate还需要用上。
#gems: [jekyll-paginate,jekyll-paginate-category]
gems: [jekyll-paginate]

collections:
  docs:
    output: true

copyright: []
#timezone: Asia/Shanghai
